### ISSUE TITLE
No module named acme.challenges

### ISSUE THREAD

**Issue by jcderose** [alex/letsencrypt-aws#21]
I'm attempting to run `letsencrypt-aws` for the first time, but I keep getting the following error message:

```
$ python letsencrypt-aws.py register me@mydomain.com
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 7, in <module>
    import acme.challenges
ImportError: No module named acme.challenges
```

I'm running Python 2.7.6. on Ubuntu 14.04.

**Comment by keichan34** [comment]
Have you tried running `pip install -r requirements.txt` first? I got that error before running the install command when I first started using it, too.

**Comment by jcderose** [comment]
@keichan34, were you able to run that command without `sudo`? When I tried, I got the error:

```
Installing collected packages: idna, enum34, ipaddress, pycparser, cffi, cryptography, pyopenssl, ndg-httpsclient, pytz, pyrfc3339, werkzeug, funcsigs, pbr, mock, dnspython, acme, futures, boto3, click, rfc3986
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 731, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 841, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 1040, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 343, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 314, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 82, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/idna'
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

**Comment by keichan34** [comment]
Yeah, check out [virtualenv](http://docs.python-guide.org/en/latest/dev/virtualenvs/)

**Comment by jcderose** [comment]
I loaded a virtualenv and was able to run `pip install -r requirements.txt` inside the venv (`my-venv`). But then I still got the same registration error.

```
(my-venv)$ python letsencrypt-aws.py register me@mydomain.com
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 7, in <module>
    import acme.challenges
ImportError: No module named acme.challenges
```

**Comment by dottodot** [comment]
I had to do `sudo pip install pytz --upgrade` to get it working

**Comment by jcderose** [comment]
@dottodot at what point did you run  `sudo pip install pytz --upgrade`? Before running `python letsencrypt-aws.py register me@mydomain.com`? Or before `pip install -r requirements.txt`?

**Comment by dottodot** [comment]
I did it after `pip install -r requirements.txt`

**Comment by jcderose** [comment]
Hm, that didn't work for me. I still get the same error when attempting to register:

```
$  cd my-le-folder/
$  virtualenv le-aws
$  source le-aws/bin/activate
(le-aws) $  git clone git@github.com:alex/letsencrypt-aws.git
(le-aws) $  cd letsencrypt-aws/
(le-aws) $  pip install -r requirements.txt
...
Successfully installed acme boto3 click cryptography pyopenssl rfc3986 ndg-httpsclient pyasn1 pyrfc3339 pytz requests six werkzeug mock botocore jmespath futures idna enum34 ipaddress cffi funcsigs pbr docutils python-dateutil pycparser
Cleaning up...

(le-aws) $  pip install pytz --upgrade
Requirement already up-to-date: pytz in /home/user/my-le-folder/le-aws/lib/python2.7/site-packages
Cleaning up..

(le-aws) $  python letsencrypt-aws.py register me@mydomain.com
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 7, in <module>
    import acme.challenges
ImportError: No module named acme.challenges
```

**Comment by jcderose** [comment]
Okay, I got it to work. The process was: 

```
$  cd my-le-folder/
$  virtualenv le-aws
$  source le-aws/bin/activate
(le-aws) $  git clone git@github.com:letsencrypt/letsencrypt.git
(le-aws) $  pip install -r letsencrypt/readthedocs.org.requirements.txt
(le-aws) $  git clone git@github.com:alex/letsencrypt-aws.git
(le-aws) $  pip install -r letsencrypt-aws/requirements.txt
(le-aws) $  python letsencrypt-aws/letsencrypt-aws.py register me@mydomain.com
```

**Comment by ahamilton9** [comment]
I'm running into this same issue, but starting clean, using a virtual environment, and running `pip install -r requirements.txt` did not fix the issue. Nor did running `sudo pip install pytz --upgrade`. I tried mimicking the exact method you described, but still get the same error.

**Comment by ahamilton9** [comment]
My fix, in case anyone ends up here:

Checked my version of pip, and it was ~1.5.0. Pip is on release 8... so I upgraded it `pip install --upgrade pip` and then re-ran `pip install -r requirements.txt`. Suddenly dnspython was now a requirement: 

```
Collecting dnspython (from acme[dns]->-r requirements.txt (line 2))
  Downloading dnspython-1.12.0.zip (230kB)
    100% |████████████████████████████████| 233kB 330kB/s 
```

And now everything works. Not sure if the cause was:
- Virtualenv's version of pip that was so far behind
- My system's version of pip that was so far behind
- Some other weird caching issue that fixed itself after restarting

But it's a place to start.

**Comment by mrbaguettefr** [comment]
I had the same issue as @ahamilton9.
I had to update `pip` from version 1.x to 8.x and `virtualenv`. My system still had the pip version bundled with Mac OS X:

```
$ sudo easy_install pip
$ sudo pip install -U virtualenv
```

then it worked as expected:

```
$ git clone https://github.com/alex/letsencrypt-aws.git
$ virtualenv venv
$ source venv/bin/activate
(venv) $ pip install -r requirements.txt
(venv) $ python letsencrypt-aws.py register me@mydomain.com
```

I think the cause is that Python cannot find the module `acme` which is extracted from the sources (first line in the `requirements.txt`) instead of a traditional `egg/wheel`.
In another words, `pip` extracts the module in `venv/src/` instead of `venv/lib/site-packages`.
This situation is better handled by earlier version of `pip` and `virtualenv`, I'm not sure which one exactly.

**Comment by abersh** [comment]
@jcderose  Hi gays I'm using django 1.6.11 python 2.7 and when python manage.py runserver i get 
this error but i install django-registration how to fix ??????

Not enabling BingMaps base layer as a BING_API_KEY is not defined in local_settings.py file.

```
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/geonode/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/geonode/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/geonode/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/geonode/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 280, in execute
    translation.activate('en-us')
  File "/home/geonode/venv/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 130, in activate
    return _trans.activate(language)
  File "/home/geonode/venv/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 188, in activate
    _active.value = translation(language)
  File "/home/geonode/venv/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/home/geonode/venv/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/home/geonode/venv/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/geonode/venv/local/lib/python2.7/site-packages/guardian/__init__.py", line 5, in <module>
    from . import checks
  File "/home/geonode/venv/local/lib/python2.7/site-packages/guardian/checks.py", line 2, in <module>
    from django.core.checks import register, Tags, Warning
ImportError: cannot import name register
```

**Comment by alex** [comment]
@abersh Your issue has nothing to do with `letsencrypt-aws`, please find a different forum for requesting support.

**Comment by tj** [comment]
@mrbaguette's comment should be in the Readme IMO, would save some trouble for non-python people
