### ISSUE TITLE
Could not unserialize key data

### ISSUE THREAD

**Issue by dottodot** [alex/letsencrypt-aws#26]
Any idea what the following error means? I have my private key install locally and is accessible

```
2016-02-15 11:18:01 [startup] 
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 486, in <module>
    cli()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "letsencrypt-aws.py", line 432, in update_certificates
    s3_client, acme_directory_url, acme_account_key
  File "letsencrypt-aws.py", line 378, in setup_acme_client
    key, password=None, backend=default_backend()
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/primitives/serialization.py", line 20, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/multibackend.py", line 282, in load_pem_private_key
    return b.load_pem_private_key(data, password)
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1606, in load_pem_private_key
    password,
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1802, in _load_key
    self._handle_key_loading_error()
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1874, in _handle_key_loading_error
    raise ValueError("Could not unserialize key data.")
ValueError: Could not unserialize key data.
```

**Comment by alex** [comment]
What format is your private key in?

On Mon, Feb 15, 2016 at 6:23 AM, Marcus Williams notifications@github.com
wrote:

> Any idea what the following error means? I have my private key install
> locally and is accessible
> 
> 2016-02-15 11:18:01 [startup]
> Traceback (most recent call last):
>   File "letsencrypt-aws.py", line 486, in <module>
>     cli()
>   File "/Library/Python/2.7/site-packages/click/core.py", line 716, in **call**
>     return self.main(_args, *_kwargs)
>   File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, *_ctx.params)
>   File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
>     return callback(_args, **kwargs)
>   File "letsencrypt-aws.py", line 432, in update_certificates
>     s3_client, acme_directory_url, acme_account_key
>   File "letsencrypt-aws.py", line 378, in setup_acme_client
>     key, password=None, backend=default_backend()
>   File "/Library/Python/2.7/site-packages/cryptography/hazmat/primitives/serialization.py", line 20, in load_pem_private_key
>     return backend.load_pem_private_key(data, password)
>   File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/multibackend.py", line 282, in load_pem_private_key
>     return b.load_pem_private_key(data, password)
>   File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1606, in load_pem_private_key
>     password,
>   File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1802, in _load_key
>     self._handle_key_loading_error()
>   File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1874, in _handle_key_loading_error
>     raise ValueError("Could not unserialize key data.")
> ValueError: Could not unserialize key data.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex/letsencrypt-aws/issues/26.

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by dottodot** [comment]
After running `python letsencrypt-aws.py register email@host.com` I pasted into a file and save as key.pem

**Comment by phthhieu** [comment]
@dottodot 
Make sure your key has this format:

```
-----BEGIN RSA PRIVATE KEY-----
# RSA key
-----END RSA PRIVATE KEY-----
```
