### ISSUE TITLE
acme.challenges.DNS01 does not exist

### ISSUE THREAD

**Issue by alantliang** [alex/letsencrypt-aws#27]
Hi, I'm running into the following issue:

```
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 521, in <module>
    cli()
  File "/home/ubuntu/le-aws/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/le-aws/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/le-aws/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/le-aws/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/le-aws/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "letsencrypt-aws.py", line 477, in update_certificates
    force_issue, domains
  File "letsencrypt-aws.py", line 383, in update_elbs
    domain.get("key_type", "rsa")
  File "letsencrypt-aws.py", line 335, in update_elb
    logger, acme_client, elb_client, route53_client, elb_name, host
  File "letsencrypt-aws.py", line 199, in start_dns_challenge
    [dns_challenge] = find_dns_challenge(authz)
  File "letsencrypt-aws.py", line 83, in find_dns_challenge
    isinstance(combo[0].chall, acme.challenges.DNS01)
AttributeError: 'module' object has no attribute 'DNS01'
```

When I print dir(acme.challenges) I get:

```
['Challenge', 'ChallengeResponse', 'ContinuityChallenge', 'DNS', 'DNSResponse', 'DVChallenge', 'HTTP01', 'HTTP01Response', 'KeyAuthorizationChallenge', 'KeyAuthorizationChallengeResponse', 'OpenSSL', 'ProofOfPossession', 'ProofOfPossessionResponse', 'RecoveryContact', 'RecoveryContactResponse', 'TLSSNI01', 'TLSSNI01Response', 'UnrecognizedChallenge', '_TokenDVChallenge', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'abc', 'crypto_util', 'errors', 'fields', 'functools', 'hashes', 'hashlib', 'jose', 'logger', 'logging', 'other', 'requests', 'socket']
```

I have run pip install -r requirements.txt
My acme version is: 0.5.0.dev0

Not sure if I'm doing something egregiously wrong, any help would be appreciated. Let me know if you need more information about my configuration.

**Comment by alex** [comment]
Did you install another version of `acme` somehow? This looks like what would happen if you installed `acme` from `master` instead of from the branch we use. What version of `pip` are you using?

**Comment by alantliang** [comment]
Ah, I was using pip 1.5 because I created a new virtualenv. I'll upgrade to 8.0.2 and see if I can fix my problem, thanks alex!

**Comment by alex** [comment]
(Unless I hear otherwise closing this)

**Comment by IzekChen** [comment]
@alantliang Hi , how did you solve the problem about the "AttributeError: 'module' object has no attribute 'DNS01'"?
I get the same problem
