### ISSUE TITLE
ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by phthhieu** [alex/letsencrypt-aws#29]
I ran this command _python letsencrypt-aws.py update-certificates_
Then I got this error:

```
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 500, in <module>
    cli()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "letsencrypt-aws.py", line 463, in update_certificates
    force_issue, domains
  File "letsencrypt-aws.py", line 362, in update_elbs
    domain.get("key_type", "rsa")
  File "letsencrypt-aws.py", line 285, in update_elb
    elb_client, elb_name, elb_port
  File "letsencrypt-aws.py", line 147, in get_load_balancer_certificate
    if listener["Listener"]["LoadBalancerPort"] == elb_port
ValueError: need more than 0 values to unpack
```

Any suggestion to fix? Thanks

**Comment by phthhieu** [comment]
Duplidate to [issues#13](https://github.com/alex/letsencrypt-aws/issues/13)
