### ISSUE TITLE
TypeError: request_domain_challenges() got an unexpected keyword argument 'new_authz_uri'

### ISSUE THREAD

**Issue by judahteng** [alex/letsencrypt-aws#30]
Hi guys, I'm running into this issue when script is running [updating-elb.request-acme-challenge]:

```
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 486, in <module>
    cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "letsencrypt-aws.py", line 449, in update_certificates
    force_issue, domains
  File "letsencrypt-aws.py", line 359, in update_elbs
    domain.get("key_type", "rsa")
  File "letsencrypt-aws.py", line 311, in update_elb
    logger, acme_client, elb_client, route53_client, elb_name, host
  File "letsencrypt-aws.py", line 173, in start_dns_challenge
    host, new_authz_uri=acme_client.directory.new_authz
TypeError: request_domain_challenges() got an unexpected keyword argument 'new_authz_uri'
```

I have run pip install -r requirements.txt. pip version is 8.0.3.

Any help is greatly appreciated.

**Comment by judahteng** [comment]
That was fast. Thanks!
