### ISSUE TITLE
Region missing

### ISSUE THREAD

**Issue by markhofmann** [alex/letsencrypt-aws#32]
I am using AWS instances based in Singapore.

When I run letsencrypt-aws on my instance, I get a 
botocore.exceptions.NoRegionError: You must specify a region.

Full error message:

```
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 486, in <module>
    cli()
  File "/app/.venv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/app/.venv/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/app/.venv/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.venv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/.venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "letsencrypt-aws.py", line 414, in update_certificates
    elb_client = session.client("elb")
  File "/app/.venv/lib/python2.7/site-packages/boto3/session.py", line 207, in client
    aws_session_token=aws_session_token, config=config)
  File "/app/.venv/lib/python2.7/site-packages/botocore/session.py", line 809, in create_client
    client_config=config, api_version=api_version)
  File "/app/.venv/lib/python2.7/site-packages/botocore/client.py", line 62, in create_client
    verify, credentials, scoped_config, client_config)
  File "/app/.venv/lib/python2.7/site-packages/botocore/client.py", line 150, in _get_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/app/.venv/lib/python2.7/site-packages/botocore/client.py", line 272, in resolve
    service_name, region_name)
  File "/app/.venv/lib/python2.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/app/.venv/lib/python2.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```

**Comment by alex** [comment]
This happens if you haven't configured boto in any way. You need to configure it using one of these options: https://boto3.readthedocs.org/en/latest/guide/configuration.html#configuring-credentials

**Comment by mikew** [comment]
Environment variables should work, yeah? Cause they're not over here:

``` bash
$ docker run \
  --rm \
  --env AWS_ACCESS_KEY_ID=... \
  --env AWS_SECRET_ACCESS_KEY=... \
  alexgaynor/letsencrypt-aws

2016-07-12 19:52:40 [startup]
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 577, in <module>
    cli()
  File "/app/.venv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/app/.venv/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/app/.venv/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.venv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/.venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "letsencrypt-aws.py", line 493, in update_certificates
    elb_client = session.client("elb")
  File "/app/.venv/lib/python2.7/site-packages/boto3/session.py", line 250, in client
    aws_session_token=aws_session_token, config=config)
  File "/app/.venv/lib/python2.7/site-packages/botocore/session.py", line 818, in create_client
    client_config=config, api_version=api_version)
  File "/app/.venv/lib/python2.7/site-packages/botocore/client.py", line 69, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/app/.venv/lib/python2.7/site-packages/botocore/client.py", line 199, in _get_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/app/.venv/lib/python2.7/site-packages/botocore/client.py", line 322, in resolve
    service_name, region_name)
  File "/app/.venv/lib/python2.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/app/.venv/lib/python2.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```

**Comment by alex** [comment]
Yup, they should, I believe you ened to specify an AWS_REGION env var (I
forget the exact name)

On Tue, Jul 12, 2016 at 3:58 PM, mikew notifications@github.com wrote:

> Environment variables should work, yeah? Cause they're not over here:
> 
> $ docker run \
>   --rm \
>   --env AWS_ACCESS_KEY_ID=... \
>   --env AWS_SECRET_ACCESS_KEY=... \
>   alexgaynor/letsencrypt-aws
> 
> 2016-07-12 19:52:40 [startup]
> Traceback (most recent call last):
>   File "letsencrypt-aws.py", line 577, in <module>
>     cli()
>   File "/app/.venv/lib/python2.7/site-packages/click/core.py", line 716, in **call**
>     return self.main(_args, *_kwargs)
>   File "/app/.venv/lib/python2.7/site-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/app/.venv/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/app/.venv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, *_ctx.params)
>   File "/app/.venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
>     return callback(_args, **kwargs)
>   File "letsencrypt-aws.py", line 493, in update_certificates
>     elb_client = session.client("elb")
>   File "/app/.venv/lib/python2.7/site-packages/boto3/session.py", line 250, in client
>     aws_session_token=aws_session_token, config=config)
>   File "/app/.venv/lib/python2.7/site-packages/botocore/session.py", line 818, in create_client
>     client_config=config, api_version=api_version)
>   File "/app/.venv/lib/python2.7/site-packages/botocore/client.py", line 69, in create_client
>     verify, credentials, scoped_config, client_config, endpoint_bridge)
>   File "/app/.venv/lib/python2.7/site-packages/botocore/client.py", line 199, in _get_client_args
>     service_name, region_name, endpoint_url, is_secure)
>   File "/app/.venv/lib/python2.7/site-packages/botocore/client.py", line 322, in resolve
>     service_name, region_name)
>   File "/app/.venv/lib/python2.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
>     partition, service_name, region_name)
>   File "/app/.venv/lib/python2.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
>     raise NoRegionError()
> botocore.exceptions.NoRegionError: You must specify a region.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/alex/letsencrypt-aws/issues/32#issuecomment-232161229,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAADBIiY4270xSUYzE_YakpO3uqFwjakks5qU_H_gaJpZM4HudDR
> .

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6
