### ISSUE TITLE
cryptography OpenSSL error

### ISSUE THREAD

**Issue by kickino** [alex/letsencrypt-aws#35]
Hey guys,
I followed the README instructions and get the following error while executing.
Can somebody help? When I search for the error it seems the problem is related to the country code in the cert. But I can't remember that I have to manual set it for LE? Can somebody have a look?
Thanks a lot in advance!
   Sebastian

```
2016-03-18 02:37:58 [startup] 
2016-03-18 02:37:58 [running] mode='single'
2016-03-18 02:37:58 [updating-elb] elb_name=u'xxxxLB'
2016-03-18 02:37:59 [updating-elb.certificate-expiration] expiration_date=datetime.date(2016, 3, 29) elb_name=u'xxxxLB '
Traceback (most recent call last):
  File "/home/ubuntu/letsencrypt-aws/letsencrypt-aws.py", line 523, in <module>
    cli()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/letsencrypt-aws/letsencrypt-aws.py", line 486, in update_certificates
    force_issue, certificate_requests
  File "/home/ubuntu/letsencrypt-aws/letsencrypt-aws.py", line 384, in update_elbs
    cert_request,
  File "/home/ubuntu/letsencrypt-aws/letsencrypt-aws.py", line 337, in update_elb
    csr = generate_csr(private_key, cert_request.hosts)
  File "/home/ubuntu/letsencrypt-aws/letsencrypt-aws.py", line 208, in generate_csr
    return csr_builder.sign(private_key, hashes.SHA256(), default_backend())
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/base.py", line 354, in sign
    return backend.create_x509_csr(self, private_key, algorithm)
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/multibackend.py", line 372, in create_x509_csr
    return b.create_x509_csr(builder, private_key, algorithm)
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1325, in create_x509_csr
    x509_req, _encode_name_gc(self, builder._subject_name)
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 158, in _encode_name_gc
    subject = _encode_name(backend, attributes)
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 153, in _encode_name
    backend.openssl_assert(res == 1)
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 719, in openssl_assert
    return binding._openssl_assert(self._lib, ok)
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 43, in _openssl_assert
    errors
cryptography.exceptions.InternalError: Unknown OpenSSL error. Please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLError(code=218603671L, lib=13, func=122, reason=151)])
```

**Comment by alex** [comment]
What domain is this certificate for?

**Comment by kickino** [comment]
```
        \"hosts\": [\”example.com www.example.com\"],
```

Oh? Is the syntax wrong? :(

**Comment by kickino** [comment]
Ah. Sorry.

After I followed https://alexgaynor.net/2016/jan/20/announcing-letsencrypt-aws/ it worked perfectly fine. Sorry!

"hosts": ["host.com", "www.host.com"],

**Comment by alex** [comment]
Ok :+1:
