### ISSUE TITLE
update-certificates returns AttributeError: 'NoneType' 

### ISSUE THREAD

**Issue by Esardes** [alex/letsencrypt-aws#38]
I am running the script from an EC2 instance in the same vpc as my EB/ELB
Here is what it returns

```
python letsencrypt-aws.py update-certificates
2016-03-22 14:24:48 [startup] 
2016-03-22 14:24:48 [running] mode='single'
2016-03-22 14:24:48 [updating-elb] elb_name=u'awseb-e-XXX'
2016-03-22 14:24:49 [updating-elb.certificate-expiration] expiration_date=datetime.date(2016, 5, 5) elb_name=u'awseb-e-XXX'
2016-03-22 14:24:49 [updating-elb.request-acme-challenge] host=u'example.com' elb_name=u'awseb-e-XXX'
2016-03-22 14:24:50 [updating-elb.create-txt-record] host=u'example.com' elb_name=u'awseb-e-XXX'
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 523, in <module>
    cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "letsencrypt-aws.py", line 486, in update_certificates
    force_issue, certificate_requests
  File "letsencrypt-aws.py", line 384, in update_elbs
    cert_request,
  File "letsencrypt-aws.py", line 344, in update_elb
    cert_request.cert_location.elb_name, host,
  File "letsencrypt-aws.py", line 252, in start_dns_challenge
    dns_challenge.validation(acme_client.key),
  File "letsencrypt-aws.py", line 161, in create_txt_record
    value,
  File "letsencrypt-aws.py", line 146, in _change_txt_record
    {"Value": '"{}"'.format(value)}
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 228, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 468, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 518, in _convert_to_request_dict
    params=api_params, model=operation_model, context=context)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/handlers.py", line 469, in fix_route53_ids
    params[name] = orig_value.split('/')[-1]
AttributeError: 'NoneType' object has no attribute 'split'

```

It correctly identifies my elb and certificate (this is the right expiration date), but then fails.
So I sudo-modified `/usr/local/lib/python2.7/site-packages/botocore/handlers.py` to print the inputs for the function `fix_route53_ids` and got : 

```
params fix_route53 
{}
model 
<botocore.model.OperationModel object at 0x7f7a65c04390>
args 
{'event_name': 'before-parameter-build.route53.ListHostedZones', 'context': {}}
params fix_route53 
{'HostedZoneId': None, 'ChangeBatch': {'Changes': [{'Action': 'CREATE', 'ResourceRecordSet': {'ResourceRecords': [{'Value': '"mX7cXXX"'}], 'Type': 'TXT', 'Name': '_acme-challenge.example.com', 'TTL': 30}}]}}
model 
<botocore.model.OperationModel object at 0x7f7a65bf8210>
args 
{'event_name': 'before-parameter-build.route53.ChangeResourceRecordSets', 'context': {}}
```

It seems params is empty while it shouldn't be. This is as far as I managed to debug it. Any help would be much appreciated. Thank you!

**Comment by alex** [comment]
It looks like the problem is that it's not finding a hosted-zone for your domain. Are any of the domains you're trying to obtain certificates for not hosted on route53?

**Comment by Esardes** [comment]
Oh my, yes. Is it enough to host the one subdomain that really matters to me on route53?

**Comment by alex** [comment]
In theory that should work. Can you tell me what hosted zomes you have, and what domains you're attempting to get a cert for?

**Comment by Esardes** [comment]
You were right, hosting the subdomain is enough (I just followed those [instructions](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/CreatingNewSubdomain.html)). After that it was a smooth ride. Thanks a lot for your help and your tool.
