### ISSUE TITLE
--force-issue raising a ValueError 

### ISSUE THREAD

**Issue by kalilou** [alex/letsencrypt-aws#43]
Hi @alex 

I really like this project and started using it yesterday to renew our certificates which we've created using letsencrypt couple days ago.

I have setup everything required for letsencrypt-aws but getting an issue with ValueError while updating-elb.wait-for-route53 is being ran. I am bit confuse, any help be much appreciated. 
Here is the stacktrace for it.

```
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 537, in <module>
    cli()
  File "/home/aws/letsencrypt-aws/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/aws/letsencrypt-aws/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/aws/letsencrypt-aws/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aws/letsencrypt-aws/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aws/letsencrypt-aws/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "letsencrypt-aws.py", line 500, in update_certificates
    force_issue, certificate_requests
  File "letsencrypt-aws.py", line 398, in update_elbs
    cert_request,
  File "letsencrypt-aws.py", line 365, in update_elb
    cert_request.cert_location.elb_name, authz_record
  File "letsencrypt-aws.py", line 297, in complete_dns_challenge
    raise ValueError("Failed verification")
ValueError: Failed verification 
```

**Comment by semanticdreamer** [comment]
@kalilou I had exact the same error and ultimately solved it by fixing the DNS for the host I needed the certificates to be issued for (single one in my case).

Highly likely (almost sure) your case is different.. but still it might be related to your DNS.

Anyway, here are the my details: from my other (main) AWS account I had only a CNAME record for the host pointing to the load balancer. Obviously this is not enough for the DNS challenge to be successful. After properly pointing via NS (NameServer) records to my host in the 2nd account everything worked like a charm.

hth

**Comment by alex** [comment]
This error will occur if setting the DNS in route53 doesn't cause it to actually be visible to DNS resolvers. @semanticdreamer gives one example of when this could happen, there may be other cases and you'll probably have to debug a bit.

**Comment by andresvia** [comment]
@kalilou I'm having the same problem, did you manage to solve it?
