### ISSUE TITLE
Install Help

### ISSUE THREAD

**Issue by tenacioustechie** [alex/letsencrypt-aws#45]
I'm a complete python hack having trouble getting this to work, I can see some others having similar trouble in the past, but I haven't found a solution in the issues. 

I'm working on a clean ubuntu server precise server. 
First up, is python 2.7.6 suitable? Or should I be using Python 3.X? (I've tried both to no avail, and I think I found suggestion that either is fine in the issues). 

Using these commands:

```
$ sudo apt-get install git
$ git clone https://github.com/alex/letsencrypt-aws.git
$ sudo apt-get install python-pip
$ pip install -r requirements.txt
```

I first hit a permissions issue with pip trying to do things in "/usr/local/lib/python2.7....". 
So I assumed that it also required root access (which worked). 

```
$ sudo pip install -r requirements.txt
```

I then expected to be able to run

```
$ python letsencrypt-aws.py register me@myemail.com
```

This threw this error 

```
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 7, in <module>
    import acme.challenges
ImportError: No module named acme.challenges
```

**Comment by tenacioustechie** [comment]
OK. I got a little further when using python virtual environments. The part i missed was updating PIP in the virtual environment using the command
$ pip install --upgrade pip

Now I still have an issue registering though. Error below. 

```
2016-04-14 05:27:54 [acme-register.generate-key] 
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 533, in <module>
    cli()
  File "/../letsencrypt-aws/leaws/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/../letsencrypt-aws/leaws/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/../letsencrypt-aws/leaws/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/../letsencrypt-aws/leaws/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/../letsencrypt-aws/leaws/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "letsencrypt-aws.py", line 516, in register
    private_key = generate_rsa_private_key()
  File "letsencrypt-aws.py", line 196, in generate_rsa_private_key
    public_exponent=65537, key_size=2048, backend=default_backend()
  File "/../letsencrypt-aws/leaws/local/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/../letsencrypt-aws/leaws/local/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
AttributeError: 'EntryPoint' object has no attribute 'resolve'
```

**Comment by alex** [comment]
`pip install -U setuptools` is in the virtualenv -- what distro are you using?

**Comment by tenacioustechie** [comment]
No, that was the part that was missed, adding that command worked fine.

**Comment by tenacioustechie** [comment]
I'm using Ubuntu 14.04 Server.

**Comment by tenacioustechie** [comment]
So for anyone reading this thread, the working combination for me on a clean Ubuntu 14.04 server was: 

$ sudo apt-get install git python-pip openssl libssl-dev
$ sudo pip install virtualenv
$ mkdir [projectname]
$ cd [projectname]
$ git clone https://github.com/alex/letsencrypt-aws.git
$ virtualenv [vmname]
$ source [vmname]/bin/activate
$ pip install --upgrade pip
$ pip install -r letsencrypt-aws/requirements.txt
$ pip install -U setuptools
$ pip install awscli

... And continue with the readme instructions for using the tool....
$ python letsencrypt-aws/letsencrypt-aws.py register [youremail]

Thanks for the help @alex
