### ISSUE TITLE
setup_acme_client issue

### ISSUE THREAD

**Issue by tenacioustechie** [alex/letsencrypt-aws#46]
I've now got the tool working to the point I can register. However on trying to update certificates I get this stack trace. 

```
(leaws)jenkins@jenkins-np:~/jobs/SSLCertificateUpdate/workspace$ python letsencrypt-aws/letsencrypt-aws.py update-certificates
2016-04-15 03:55:23 [startup] 
Traceback (most recent call last):
  File "letsencrypt-aws/letsencrypt-aws.py", line 533, in <module>
    cli()
  File "/var/lib/jenkins/jobs/SSLCertificateUpdate/workspace/leaws/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/var/lib/jenkins/jobs/SSLCertificateUpdate/workspace/leaws/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/var/lib/jenkins/jobs/SSLCertificateUpdate/workspace/leaws/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/lib/jenkins/jobs/SSLCertificateUpdate/workspace/leaws/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/lib/jenkins/jobs/SSLCertificateUpdate/workspace/leaws/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "letsencrypt-aws/letsencrypt-aws.py", line 467, in update_certificates
    s3_client, acme_directory_url, acme_account_key
  File "letsencrypt-aws/letsencrypt-aws.py", line 401, in setup_acme_client
    with open(uri.path) as f:
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

I've loaded config using the export statement for one ELB certificate. 
I've used pip to import aws cli and setup awscli for the user running the script. 
AwsCli is using an IAM user with access as specified in the readme.md via a group in IAM. 

Any help would be appreciated.

**Comment by alex** [comment]
What's `acme_account_key` in your configuration?

**Comment by tenacioustechie** [comment]
"acme_account_key": "file://user.pem"
which there is a file in the current directory for user.pem which was produced by the register command. 

I moved it to a full path and it has worked, so that was the problem. I'm going to experiment, as I don't want to specify the full path to the pem, just assume its in the local directory.
