### ISSUE TITLE
ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by vaindil** [alex/letsencrypt-aws#71]
I'm getting the same error as in #34 when running with 2.7, Windows 10 x64. On 3.5 I'm getting a different error (below). I messed around with it for a while but couldn't figure out how to get past it.

```
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 577, in <module>
    cli()
  File "C:\Users\Steven\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Steven\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "C:\Users\Steven\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Steven\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Steven\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "letsencrypt-aws.py", line 540, in update_certificates
    force_issue, certificate_requests
  File "letsencrypt-aws.py", line 432, in update_certs
    cert_request,
  File "letsencrypt-aws.py", line 344, in update_cert
    current_cert = cert_request.cert_location.get_current_certificate()
  File "letsencrypt-aws.py", line 86, in get_current_certificate
    for listener in description["ListenerDescriptions"]
ValueError: not enough values to unpack (expected 1, got 0)
```

**Comment by vaindil** [comment]
This is actually #13, I missed that when going through the issues before I added this one. Sorry!
