### ISSUE TITLE
TypeError: must be X509, not ComparableX509

### ISSUE THREAD

**Issue by bumpmann** [alex/letsencrypt-aws#84]
I get it work until:

```
2016-09-28 18:09:40 [updating-elb.delete-txt-record] host=u'mysite.io' elb_name=u'mysite-vpc-elb'
Traceback (most recent call last):
  File "./letsencrypt-aws.py", line 577, in <module>
    cli()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./letsencrypt-aws.py", line 540, in update_certificates
    force_issue, certificate_requests
  File "./letsencrypt-aws.py", line 432, in update_certs
    cert_request,
  File "./letsencrypt-aws.py", line 404, in update_cert
    authorizations, csr
  File "./letsencrypt-aws.py", line 332, in request_certificate
    OpenSSL.crypto.FILETYPE_PEM, cert_response.body
TypeError: must be X509, not ComparableX509
```

pip install received these versions:
`Successfully installed acme boto3-1.4.0 botocore-1.4.57 cffi-1.8.3 click-6.6 cryptography-1.5.2 dnspython-1.14.0 docutils-0.12 enum34-1.1.6 funcsigs-1.0.2 futures-3.0.5 idna-2.1 ipaddress-1.0.17 jmespath-0.9.0 mock-2.0.0 ndg-httpsclient-0.4.2 pbr-1.10.0 pyasn1-0.1.9 pycparser-2.14 pyopenssl-0.13.1 pyrfc3339-1.0 python-dateutil-1.5 pytz-2013.7 requests-2.11.1 rfc3986-0.4.1 s3transfer-0.1.4 setuptools-1.1.6 six-1.4.1`

**Comment by bumpmann** [comment]
Nevermind, just had to update pyopenssl manually on mac

`easy_install PyOpenSSL`
